create table if not exists public.respuestas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  tipo_registro text not null check (tipo_registro in ('unidad', 'consultorio')),
  entidad text,
  usuario_nombre text,
  usuario_email text,
  clues_imb text not null,
  nombre_de_la_unidad text,
  categoria_gerencial_ampliada text,
  internet text check (internet in ('SI', 'NO', 'PENDIENTE')),
  consultorios integer check (consultorios >= 0),
  consultorio integer,
  turno text,
  turno_consultorio text,
  habilitado boolean,
  causas_inhabilitacion text not null default '',
  medicos_generales integer check (medicos_generales is null or medicos_generales >= 0),
  catalogo_version integer not null default 1
);

alter table public.respuestas
  add column if not exists consultorios integer
    check (consultorios >= 0),
  add column if not exists habilitado boolean,
  add column if not exists causas_inhabilitacion text not null default '',
  add column if not exists medicos_generales integer
    check (medicos_generales is null or medicos_generales >= 0),
  add column if not exists turno_consultorio text,
  add column if not exists catalogo_version integer not null default 1;

do $columns$
declare
  pregunta_id integer;
begin
  for pregunta_id in 1..65 loop
    execute format(
      'alter table public.respuestas add column if not exists %I integer check (%I is null or %I >= 0)',
      'p_' || pregunta_id, 'p_' || pregunta_id, 'p_' || pregunta_id
    );
  end loop;
end;
$columns$;

alter table public.respuestas
  drop constraint if exists respuestas_consultorios_check;

alter table public.respuestas
  add constraint respuestas_consultorios_check check (consultorios >= 0);

do $migration$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'respuestas'
      and column_name = 'causas_inhabilitacion'
      and udt_name = '_text'
  ) then
    execute $sql$
      alter table public.respuestas
        alter column causas_inhabilitacion drop default,
        alter column causas_inhabilitacion type text
          using array_to_string(causas_inhabilitacion, ', '),
        alter column causas_inhabilitacion set default ''
    $sql$;
  end if;
end;
$migration$;

alter table public.respuestas
  drop constraint if exists respuestas_tipo_datos_check,
  drop constraint if exists respuestas_condicion_funcionamiento_check;

alter table public.respuestas
  drop column if exists condicion_funcionamiento;

alter table public.respuestas
  drop constraint if exists respuestas_turno_check,
  drop constraint if exists respuestas_turno_consultorio_check;

alter table public.respuestas
  add constraint respuestas_turno_consultorio_check check (
    turno_consultorio is null or turno_consultorio in ('Matutino', 'Vespertino', 'Ambos')
  );

alter table public.respuestas
  drop constraint if exists respuestas_tipo_registro_check,
  drop constraint if exists respuestas_json_objeto_check,
  drop constraint if exists horarios_json_objeto_check,
  add constraint respuestas_tipo_registro_check
    check (tipo_registro in ('unidad', 'consultorio')),
  add constraint respuestas_tipo_datos_check check (
    (tipo_registro = 'unidad' and consultorio is null and turno is null)
    or
    (tipo_registro = 'consultorio' and consultorio > 0
      and internet is null and consultorios is null)
  );

create unique index if not exists respuestas_unidad_clues_uidx
  on public.respuestas (clues_imb)
  where tipo_registro = 'unidad';

create unique index if not exists respuestas_consultorio_uidx
  on public.respuestas (clues_imb, consultorio)
  where tipo_registro = 'consultorio';

create index if not exists respuestas_clues_idx on public.respuestas (clues_imb);

comment on column public.respuestas.consultorio is
  'Número de consultorio para filas de configuración y equipamiento.';

comment on column public.respuestas.turno is
  'Horarios compactos separados por coma; el sufijo -med indica disponibilidad de médico.';

comment on column public.respuestas.turno_consultorio is
  'Turno general del consultorio: Matutino, Vespertino o Ambos.';

comment on column public.respuestas.medicos_generales is
  'Número de médicos generales; solo se usa en la fila del consultorio.';

comment on column public.respuestas.catalogo_version is
  'Versión del catálogo; las cantidades se almacenan en columnas p_ID.';

create or replace function public.proteger_borrado_respuestas()
returns trigger
language plpgsql
as $$
begin
  if current_setting('app.permitir_borrado_respuestas', true) is distinct from 'on' then
    raise exception 'Borrado bloqueado: use la función autorizada para eliminar respuestas.';
  end if;
  return null;
end;
$$;

drop trigger if exists respuestas_bloquear_delete on public.respuestas;
create trigger respuestas_bloquear_delete
before delete on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

drop trigger if exists respuestas_bloquear_truncate on public.respuestas;
create trigger respuestas_bloquear_truncate
before truncate on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

create or replace function public.eliminar_respuestas_unidad(p_clues text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_eliminadas integer;
begin
  if nullif(trim(p_clues), '') is null then
    raise exception 'CLUES es obligatoria';
  end if;

  perform set_config('app.permitir_borrado_respuestas', 'on', true);

  delete from public.respuestas
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'consultorio';

  get diagnostics filas_eliminadas = row_count;

  return filas_eliminadas;
end;
$$;

revoke all on function public.eliminar_respuestas_unidad(text) from public, authenticated;
grant execute on function public.eliminar_respuestas_unidad(text) to anon, service_role;

create or replace function public.eliminar_horarios_turno(
  p_clues text,
  p_consultorio integer,
  p_turno text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_actualizadas integer;
  prefijo text := lower(p_turno) || '-';
begin
  if nullif(trim(p_clues), '') is null
    or p_consultorio <= 0
    or p_turno not in ('Matutino', 'Vespertino') then
    raise exception 'Parámetros de turno inválidos';
  end if;

  update public.respuestas
  set turno = (
        select nullif(string_agg(trim(entrada), ', '), '')
        from unnest(string_to_array(coalesce(turno, ''), ',')) as valores(entrada)
        where trim(entrada) not like prefijo || '%'
      ),
      fecha_registro = now()
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'consultorio'
    and consultorio = p_consultorio;

  get diagnostics filas_actualizadas = row_count;
  return filas_actualizadas;
end;
$$;

revoke all on function public.eliminar_horarios_turno(text, integer, text) from public, authenticated;
grant execute on function public.eliminar_horarios_turno(text, integer, text) to anon, service_role;

create or replace function public.eliminar_datos_consultorio_deshabilitado(
  p_clues text,
  p_consultorio integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_actualizadas integer;
  asignaciones text;
begin
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0 then
    raise exception 'Parámetros de consultorio inválidos';
  end if;

  select string_agg(format('%I = null', nombre), ', ')
  into asignaciones
  from (
    select 'p_' || numero as nombre from generate_series(1, 65) as numeros(numero)
  ) columnas;

  execute format(
    'update public.respuestas set %s, turno = null, turno_consultorio = null, medicos_generales = null, fecha_registro = now() where clues_imb = $1 and tipo_registro = ''consultorio'' and consultorio = $2',
    asignaciones
  ) using upper(trim(p_clues)), p_consultorio;

  get diagnostics filas_actualizadas = row_count;
  return filas_actualizadas;
end;
$$;

revoke all on function public.eliminar_datos_consultorio_deshabilitado(text, integer) from public, authenticated;
grant execute on function public.eliminar_datos_consultorio_deshabilitado(text, integer) to anon, service_role;

create or replace function public.guardar_respuesta_consultorio(
  p_clues text,
  p_consultorio integer,
  p_pregunta_id text,
  p_valor integer,
  p_entidad text,
  p_usuario_nombre text,
  p_usuario_email text,
  p_nombre_unidad text
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  marca_tiempo timestamptz := now();
  columna text;
begin
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0
    or p_pregunta_id !~ '^[0-9]+$'
    or p_pregunta_id::integer not between 1 and 65
    or p_valor < 0 then
    raise exception 'Respuesta de equipamiento inválida';
  end if;

  columna := 'p_' || p_pregunta_id;

  insert into public.respuestas (
    fecha_registro, tipo_registro, entidad, usuario_nombre, usuario_email,
    clues_imb, nombre_de_la_unidad, consultorio, catalogo_version
  ) values (
    marca_tiempo, 'consultorio', p_entidad, p_usuario_nombre, p_usuario_email,
    upper(trim(p_clues)), p_nombre_unidad, p_consultorio, 1
  )
  on conflict (clues_imb, consultorio) where tipo_registro = 'consultorio'
  do update set
    fecha_registro = excluded.fecha_registro,
    entidad = excluded.entidad,
    usuario_nombre = excluded.usuario_nombre,
    usuario_email = excluded.usuario_email,
    nombre_de_la_unidad = excluded.nombre_de_la_unidad,
    catalogo_version = 1;

  execute format(
    'update public.respuestas set %I = $1 where clues_imb = $2 and tipo_registro = ''consultorio'' and consultorio = $3',
    columna
  ) using p_valor, upper(trim(p_clues)), p_consultorio;

  return marca_tiempo;
end;
$$;

create or replace function public.guardar_horario_consultorio(
  p_clues text,
  p_consultorio integer,
  p_slot text,
  p_campo text,
  p_valor boolean,
  p_entidad text,
  p_usuario_nombre text,
  p_usuario_email text,
  p_nombre_unidad text
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  marca_tiempo timestamptz := now();
  partes text[];
  clave text;
  entradas text[];
  horario_actual text;
begin
  partes := regexp_match(p_slot, '^(Matutino|Vespertino) - (lunes|martes|miercoles|jueves|viernes|sabado|domingo)$');
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0
    or partes is null
    or p_campo not in ('habilitado', 'medico_disponible') then
    raise exception 'Horario inválido';
  end if;

  clave := lower(partes[1]) || '-' || partes[2];

  insert into public.respuestas (
    fecha_registro, tipo_registro, entidad, usuario_nombre, usuario_email,
    clues_imb, nombre_de_la_unidad, consultorio, catalogo_version
  ) values (
    marca_tiempo, 'consultorio', p_entidad, p_usuario_nombre, p_usuario_email,
    upper(trim(p_clues)), p_nombre_unidad, p_consultorio, 1
  )
  on conflict (clues_imb, consultorio) where tipo_registro = 'consultorio'
  do update set
    fecha_registro = excluded.fecha_registro,
    entidad = excluded.entidad,
    usuario_nombre = excluded.usuario_nombre,
    usuario_email = excluded.usuario_email,
    nombre_de_la_unidad = excluded.nombre_de_la_unidad;

  select turno into horario_actual
  from public.respuestas
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'consultorio'
    and consultorio = p_consultorio
  for update;

  select coalesce(array_agg(trim(entrada)) filter (where trim(entrada) <> ''), array[]::text[])
  into entradas
  from unnest(string_to_array(coalesce(horario_actual, ''), ',')) as valores(entrada);

  if p_campo = 'habilitado' then
    if p_valor then
      if not (clave = any(entradas)) and not ((clave || '-med') = any(entradas)) then
        entradas := array_append(entradas, clave);
      end if;
    else
      entradas := array_remove(array_remove(entradas, clave), clave || '-med');
    end if;
  elsif p_valor and clave = any(entradas) then
    entradas := array_replace(entradas, clave, clave || '-med');
  elsif not p_valor and (clave || '-med') = any(entradas) then
    entradas := array_replace(entradas, clave || '-med', clave);
  end if;

  update public.respuestas
  set turno = nullif(array_to_string(entradas, ', '), ''),
      fecha_registro = marca_tiempo
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'consultorio'
    and consultorio = p_consultorio;

  return marca_tiempo;
end;
$$;

revoke all on function public.guardar_respuesta_consultorio(text, integer, text, integer, text, text, text, text) from public, authenticated;
grant execute on function public.guardar_respuesta_consultorio(text, integer, text, integer, text, text, text, text) to anon, service_role;
revoke all on function public.guardar_horario_consultorio(text, integer, text, text, boolean, text, text, text, text) from public, authenticated;
grant execute on function public.guardar_horario_consultorio(text, integer, text, text, boolean, text, text, text, text) to anon, service_role;

alter table public.respuestas enable row level security;

grant select, insert, update on table public.respuestas to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists respuestas_anon_select on public.respuestas;
create policy respuestas_anon_select
  on public.respuestas for select
  to anon
  using (true);

drop policy if exists respuestas_anon_insert on public.respuestas;
create policy respuestas_anon_insert
  on public.respuestas for insert
  to anon
  with check (true);

drop policy if exists respuestas_anon_update on public.respuestas;
create policy respuestas_anon_update
  on public.respuestas for update
  to anon
  using (true)
  with check (true);
