-- Normalizacion de public.respuestas: separa unidades, usuarios, consultorios
-- y respuestas_equipamiento (EAV) para eliminar el bloat por UPDATE repetido
-- sobre filas anchas (83 columnas). La tabla public.respuestas se conserva
-- intacta como respaldo/historico; deja de ser usada por la aplicacion.

-- 1. ESQUEMA NORMALIZADO
-- =======================

create table if not exists public.unidades (
  clues_imb text primary key,
  entidad text,
  nombre_de_la_unidad text,
  categoria_gerencial_ampliada text,
  internet text check (internet in ('SI','NO','PENDIENTE')),
  consultorios integer check (consultorios >= 0),
  fecha_registro timestamptz not null default now()
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  email text not null unique,
  nombre text
);

alter table public.unidades
  add column if not exists usuario_id bigint references public.usuarios(id);

create index if not exists unidades_usuario_id_idx on public.unidades (usuario_id);

create table if not exists public.consultorios (
  id bigint generated by default as identity primary key,
  unidad_clues text not null references public.unidades(clues_imb) on delete cascade,
  numero integer not null check (numero > 0),
  usuario_id bigint references public.usuarios(id),
  fecha_registro timestamptz not null default now(),
  turno_consultorio text check (turno_consultorio in ('Matutino','Vespertino','Ambos')),
  turno text,
  habilitado boolean,
  causas_inhabilitacion text not null default '',
  medicos_generales integer check (medicos_generales >= 0),
  catalogo_version integer not null default 1,
  unique (unidad_clues, numero)
);

create index if not exists consultorios_unidad_clues_idx on public.consultorios (unidad_clues);
create index if not exists consultorios_usuario_id_idx on public.consultorios (usuario_id);

create table if not exists public.respuestas_equipamiento (
  consultorio_id bigint not null references public.consultorios(id) on delete cascade,
  pregunta_id smallint not null check (pregunta_id between 1 and 65),
  cantidad integer not null check (cantidad >= 0),
  primary key (consultorio_id, pregunta_id)
);

-- 2. BACKFILL DESDE public.respuestas (idempotente)
-- ====================================================

insert into public.unidades (clues_imb, entidad, nombre_de_la_unidad, internet, consultorios, fecha_registro)
select clues_imb, entidad, nombre_de_la_unidad, internet, consultorios, fecha_registro
from public.respuestas
where tipo_registro = 'unidad'
on conflict (clues_imb) do nothing;

insert into public.usuarios (email, nombre)
select distinct lower(trim(usuario_email)), usuario_nombre
from public.respuestas
where usuario_email is not null and nullif(trim(usuario_email), '') is not null
on conflict (email) do nothing;

insert into public.consultorios (unidad_clues, numero, usuario_id, fecha_registro, turno_consultorio, turno, habilitado, causas_inhabilitacion, medicos_generales, catalogo_version)
select r.clues_imb, r.consultorio, u.id, r.fecha_registro, r.turno_consultorio, r.turno, r.habilitado, r.causas_inhabilitacion, r.medicos_generales, r.catalogo_version
from public.respuestas r
left join public.usuarios u on lower(trim(r.usuario_email)) = u.email
where r.tipo_registro = 'consultorio'
  and exists (select 1 from public.unidades un where un.clues_imb = r.clues_imb)
on conflict (unidad_clues, numero) do nothing;

insert into public.respuestas_equipamiento (consultorio_id, pregunta_id, cantidad)
select c.id, substring(kv.key from 3)::smallint, kv.value::integer
from public.respuestas r
join public.consultorios c on c.unidad_clues = r.clues_imb and c.numero = r.consultorio
cross join lateral jsonb_each_text(to_jsonb(r)) as kv(key, value)
where r.tipo_registro = 'consultorio'
  and kv.key ~ '^p_[0-9]+$'
  and kv.value is not null
on conflict (consultorio_id, pregunta_id) do nothing;

-- 3. RPCs REESCRITAS (resuelve el bloat: reescriben filas de ~60-70 bytes
-- en respuestas_equipamiento en lugar de filas de ~700 bytes en respuestas)
-- =========================================================================

create or replace function public.guardar_respuesta_consultorio(
  p_clues text,
  p_consultorio integer,
  p_pregunta_id text,
  p_valor integer,
  p_usuario_email text,
  p_usuario_nombre text
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  marca_tiempo timestamptz := now();
  v_usuario_id bigint;
  v_consultorio_id bigint;
begin
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0
    or p_pregunta_id !~ '^[0-9]+$'
    or p_pregunta_id::integer not between 1 and 65
    or p_valor < 0 then
    raise exception 'Respuesta de equipamiento inválida';
  end if;

  if nullif(trim(p_usuario_email), '') is not null then
    insert into usuarios (email, nombre) values (lower(trim(p_usuario_email)), p_usuario_nombre)
      on conflict (email) do update set nombre = excluded.nombre
      returning id into v_usuario_id;
  end if;

  insert into consultorios (unidad_clues, numero, usuario_id, fecha_registro)
    values (upper(trim(p_clues)), p_consultorio, v_usuario_id, marca_tiempo)
    on conflict (unidad_clues, numero) do update
      set usuario_id = coalesce(excluded.usuario_id, consultorios.usuario_id),
          fecha_registro = excluded.fecha_registro
    returning id into v_consultorio_id;

  insert into respuestas_equipamiento (consultorio_id, pregunta_id, cantidad)
    values (v_consultorio_id, p_pregunta_id::smallint, p_valor)
    on conflict (consultorio_id, pregunta_id) do update set cantidad = excluded.cantidad;

  return marca_tiempo;
end;
$$;

create or replace function public.guardar_horario_consultorio(
  p_clues text,
  p_consultorio integer,
  p_slot text,
  p_campo text,
  p_valor boolean,
  p_usuario_email text,
  p_usuario_nombre text
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  marca_tiempo timestamptz := now();
  partes text[];
  clave text;
  entradas text[];
  horario_actual text;
  v_usuario_id bigint;
  v_consultorio_id bigint;
begin
  partes := regexp_match(p_slot, '^(Matutino|Vespertino) - (lunes|martes|miercoles|jueves|viernes|sabado|domingo)$');
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0
    or partes is null
    or p_campo not in ('habilitado', 'medico_disponible') then
    raise exception 'Horario inválido';
  end if;

  clave := lower(partes[1]) || '-' || partes[2];

  if nullif(trim(p_usuario_email), '') is not null then
    insert into usuarios (email, nombre) values (lower(trim(p_usuario_email)), p_usuario_nombre)
      on conflict (email) do update set nombre = excluded.nombre
      returning id into v_usuario_id;
  end if;

  insert into consultorios (unidad_clues, numero, usuario_id, fecha_registro)
    values (upper(trim(p_clues)), p_consultorio, v_usuario_id, marca_tiempo)
    on conflict (unidad_clues, numero) do update
      set usuario_id = coalesce(excluded.usuario_id, consultorios.usuario_id),
          fecha_registro = excluded.fecha_registro
    returning id into v_consultorio_id;

  select turno into horario_actual from consultorios where id = v_consultorio_id for update;

  select coalesce(array_agg(trim(entrada)) filter (where trim(entrada) <> ''), array[]::text[])
  into entradas
  from unnest(string_to_array(coalesce(horario_actual, ''), ',')) as valores(entrada);

  if p_campo = 'habilitado' then
    if p_valor then
      if not (clave = any(entradas)) and not ((clave || '-med') = any(entradas)) then
        entradas := array_append(entradas, clave);
      end if;
    else
      entradas := array_remove(array_remove(entradas, clave), clave || '-med');
    end if;
  elsif p_valor and clave = any(entradas) then
    entradas := array_replace(entradas, clave, clave || '-med');
  elsif not p_valor and (clave || '-med') = any(entradas) then
    entradas := array_replace(entradas, clave || '-med', clave);
  end if;

  update consultorios
  set turno = nullif(array_to_string(entradas, ', '), ''),
      fecha_registro = marca_tiempo
  where id = v_consultorio_id;

  return marca_tiempo;
end;
$$;

create or replace function public.eliminar_datos_consultorio_deshabilitado(
  p_clues text,
  p_consultorio integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_consultorio_id bigint;
  filas_eliminadas integer;
begin
  if nullif(trim(p_clues), '') is null or p_consultorio <= 0 then
    raise exception 'Parámetros de consultorio inválidos';
  end if;

  select id into v_consultorio_id
  from consultorios
  where unidad_clues = upper(trim(p_clues)) and numero = p_consultorio;

  if v_consultorio_id is null then
    return 0;
  end if;

  delete from respuestas_equipamiento where consultorio_id = v_consultorio_id;
  get diagnostics filas_eliminadas = row_count;

  update consultorios
  set turno = null, turno_consultorio = null, medicos_generales = null, fecha_registro = now()
  where id = v_consultorio_id;

  return filas_eliminadas;
end;
$$;

create or replace function public.eliminar_respuestas_unidad(p_clues text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_eliminadas integer;
begin
  if nullif(trim(p_clues), '') is null then
    raise exception 'CLUES es obligatoria';
  end if;

  delete from public.consultorios
  where unidad_clues = upper(trim(p_clues));

  get diagnostics filas_eliminadas = row_count;

  return filas_eliminadas;
end;
$$;

create or replace function public.eliminar_horarios_turno(
  p_clues text,
  p_consultorio integer,
  p_turno text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_actualizadas integer;
  prefijo text := lower(p_turno) || '-';
begin
  if nullif(trim(p_clues), '') is null
    or p_consultorio <= 0
    or p_turno not in ('Matutino', 'Vespertino') then
    raise exception 'Parámetros de turno inválidos';
  end if;

  update public.consultorios
  set turno = (
        select nullif(string_agg(trim(entrada), ', '), '')
        from unnest(string_to_array(coalesce(turno, ''), ',')) as valores(entrada)
        where trim(entrada) not like prefijo || '%'
      ),
      fecha_registro = now()
  where unidad_clues = upper(trim(p_clues))
    and numero = p_consultorio;

  get diagnostics filas_actualizadas = row_count;
  return filas_actualizadas;
end;
$$;

revoke all on function public.guardar_respuesta_consultorio(text, integer, text, integer, text, text) from public, authenticated;
grant execute on function public.guardar_respuesta_consultorio(text, integer, text, integer, text, text) to anon, service_role;
revoke all on function public.guardar_horario_consultorio(text, integer, text, text, boolean, text, text) from public, authenticated;
grant execute on function public.guardar_horario_consultorio(text, integer, text, text, boolean, text, text) to anon, service_role;
revoke all on function public.eliminar_datos_consultorio_deshabilitado(text, integer) from public, authenticated;
grant execute on function public.eliminar_datos_consultorio_deshabilitado(text, integer) to anon, service_role;
revoke all on function public.eliminar_respuestas_unidad(text) from public, authenticated;
grant execute on function public.eliminar_respuestas_unidad(text) to anon, service_role;
revoke all on function public.eliminar_horarios_turno(text, integer, text) from public, authenticated;
grant execute on function public.eliminar_horarios_turno(text, integer, text) to anon, service_role;

-- 4. RLS Y PERMISOS PARA LAS TABLAS NUEVAS
-- ===========================================

alter table public.unidades enable row level security;
alter table public.usuarios enable row level security;
alter table public.consultorios enable row level security;
alter table public.respuestas_equipamiento enable row level security;

grant select, insert, update on table public.unidades to anon;
grant select, insert, update on table public.usuarios to anon;
grant select, insert, update on table public.consultorios to anon;
grant select, insert, update on table public.respuestas_equipamiento to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists unidades_anon_select on public.unidades;
create policy unidades_anon_select on public.unidades for select to anon using (true);
drop policy if exists unidades_anon_insert on public.unidades;
create policy unidades_anon_insert on public.unidades for insert to anon with check (true);
drop policy if exists unidades_anon_update on public.unidades;
create policy unidades_anon_update on public.unidades for update to anon using (true) with check (true);

drop policy if exists usuarios_anon_select on public.usuarios;
create policy usuarios_anon_select on public.usuarios for select to anon using (true);
drop policy if exists usuarios_anon_insert on public.usuarios;
create policy usuarios_anon_insert on public.usuarios for insert to anon with check (true);
drop policy if exists usuarios_anon_update on public.usuarios;
create policy usuarios_anon_update on public.usuarios for update to anon using (true) with check (true);

drop policy if exists consultorios_anon_select on public.consultorios;
create policy consultorios_anon_select on public.consultorios for select to anon using (true);
drop policy if exists consultorios_anon_insert on public.consultorios;
create policy consultorios_anon_insert on public.consultorios for insert to anon with check (true);
drop policy if exists consultorios_anon_update on public.consultorios;
create policy consultorios_anon_update on public.consultorios for update to anon using (true) with check (true);

drop policy if exists respuestas_equipamiento_anon_select on public.respuestas_equipamiento;
create policy respuestas_equipamiento_anon_select on public.respuestas_equipamiento for select to anon using (true);
drop policy if exists respuestas_equipamiento_anon_insert on public.respuestas_equipamiento;
create policy respuestas_equipamiento_anon_insert on public.respuestas_equipamiento for insert to anon with check (true);
drop policy if exists respuestas_equipamiento_anon_update on public.respuestas_equipamiento;
create policy respuestas_equipamiento_anon_update on public.respuestas_equipamiento for update to anon using (true) with check (true);

comment on table public.unidades is 'Datos generales de la unidad medica (una fila por clues_imb).';
comment on table public.usuarios is 'Personas que capturan datos, deduplicadas por email.';
comment on table public.consultorios is 'Configuracion y horarios por consultorio; reemplaza filas tipo_registro=consultorio de public.respuestas.';
comment on table public.respuestas_equipamiento is 'Cantidades de equipamiento por consultorio y pregunta (EAV); reemplaza columnas p_1..p_65.';
comment on table public.respuestas is 'Tabla legada, conservada como respaldo historico. La aplicacion ya no la usa; ver unidades/consultorios/respuestas_equipamiento.';
